openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /api/back-office/medical-examination-histories/{id}:
    get:
      tags:
        - medical-examination-history-controller
      operationId: getExaminationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Уникальный идентификатор осмотра
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/MedicalExaminationHistoryCard"

components:
  schemas:
    MedicalExaminationHistoryResult:
      type: object
      description: Результат медицинского осмотра
      properties:
        dateTime:
          type: integer
          format: int64
          description: Дата/время вынесения решения или остановки осмотра
        type:
          type: string
          description: Тип результата осмотра
        reason:
          type: string
          description: Причина отказа/остановки осмотра
        conclusion:
          type: string
          description: Заключение
    MedicalExaminationHistoryPatient:
      type: object
      description: Данные о пациенте
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор пациента
        lastName:
          type: string
          description: Фамилия
        firstName:
          type: string
          description: Имя
        middleName:
          type: string
          description: Отчество
        birthDate:
          type: string
          format: date
          description: Дата рождения
        staffNumber:
          type: string
          description: Табельный номер
        position:
          type: string
          description: Должность
        organizationName:
          type: string
          description: Название организации
        photoUrl:
          type: string
          description: Ссылка на фото профиля
    MedicalExaminationHistoryDoctor:
      type: object
      description: Данные о враче
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор врача
        lastName:
          type: string
          description: Фамилия
        firstName:
          type: string
          description: Имя
        middleName:
          type: string
          description: Отчество
        organizationName:
          type: string
          description: Название организации
    MedicalExaminationHistoryMeasurement:
      type: object
      description: Данные измерений
      properties:
        code:
          type: string
          description: Код типа измерения
        value:
          type: string
          description: Значение измерения
        referenceStatus:
          type: string
          enum:
            - IN_RANGE
            - NOT_IN_RANGE
            - NONE
          description: Информация о нахождении результата измерений в допустимом диапазоне
        photoUrl:
          type: string
          description: Ссылка на фото
    MedicalExaminationHistoryCard:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор осмотра
        type:
          type: string
          description: Тип осмотра новый
        status:
          type: string
          description: Статус осмотра
        dateTime:
          type: integer
          format: int64
          description:  Дата/время осмотра
        signed:
          type: boolean
          description: Флаг подписи результатов осмотра УКЭП
        examinationVideoUrl:
          type: string
          description: Ссылка на видео осмотра
        authorizationPhotoUrl:
          type: string
          description: Ссылка на фото при авторизации
        result:
          $ref: "#/components/schemas/MedicalExaminationHistoryResult"
        patient:
          $ref: "#/components/schemas/MedicalExaminationHistoryPatient"
        doctor:
          $ref: "#/components/schemas/MedicalExaminationHistoryDoctor"
        measurements:
          type: array
          items:
            $ref: "#/components/schemas/MedicalExaminationHistoryMeasurement"